server:
  port: ${PORT:8081}

spring:
  application:
    name: java-reactor
  jackson:
    default-property-inclusion: non_null

app:
  max-count: ${MAX_COUNT:200000}
  flatmap:
    concurrency: ${FLATMAP_CONCURRENCY:64}
  downstream:
    timeout-ms: ${DOWNSTREAM_TIMEOUT_MS:2000}
    retry-attempts: ${RETRY_ATTEMPTS:1}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.fernandoglizt.reactive.javareactor: ${LOG_LEVEL:INFO}
    reactor.netty: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /dev/stdout
